import streamlit as st
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from PIL import Image


questions = [
    ("Python is a ______ language?", ["Compiled", "Interpreted", "Assembly", "Machine"], "Interpreted"),
    ("Which keyword defines a function?", ["func", "define", "def", "lambda"], "def"),
    ("What is the output of 2**3?", ["5", "6", "8", "9"], "8"),
    ("Which data type is immutable?", ["List", "Set", "Dict", "Tuple"], "Tuple"),
    ("What does 'len()' return?", ["Type", "Length", "Sum", "Size"], "Length"),
    ("Python files have which extension?", [".py", ".pt", ".pyt", ".python"], ".py"),
    ("What is used to import a module?", ["import", "include", "require", "load"], "import"),
    ("Which loop executes at least once?", ["for", "while", "do-while", "none"], "do-while"),
    ("Python is developed by ______?", ["Google", "Microsoft", "Guido van Rossum", "Elon Musk"], "Guido van Rossum"),
    ("Lists are enclosed in ______?", ["{}", "()", "[]", "<>"], "[]")
]


def generate_certificate(name, email, department, score):
    file_name = f"{name}_certificate.pdf"
    c = canvas.Canvas(file_name, pagesize=letter)
    width, height = letter
    margin = 30  # distance from edges
    c.setLineWidth(4)
    c.setStrokeColor(colors.darkblue)
    c.rect(margin, margin, width - 2 * margin, height - 2 * margin)

    c.setLineWidth(1.5)
    c.setStrokeColor(colors.lightblue)
    c.rect(margin + 10, margin + 10, width - 2 * (margin + 10), height - 2 * (margin + 10))
    
    c.setFont("Helvetica-Bold", 26)
    c.setFillColor(colors.darkblue)
    c.drawCentredString(width / 2, height - 150, "Certificate of Achievement")

    logo_width, logo_height = 120, 100
    x = (width - logo_width) / 2
    y = height - 280
    c.drawImage(r"C:\Users\Lokesh\Downloads\techmaa_org.jpg", x, y, width=logo_width, height=logo_height, mask='auto')

    c.setFont("Helvetica", 15)
    c.drawCentredString(width/2, y - 70, f"This certifies that candidate has demonstrated the ")
    c.drawCentredString(width/2, y - 90, f"outstanding performance in the Quiz. ")

    c.setFont("Helvetica-Bold", 20)
    c.setFillColor(colors.darkgreen)
    c.drawCentredString(width/2, y - 120, name)

    c.setFont("Helvetica", 14)
    c.drawCentredString(width/2, y - 140, f"Department: {department}")
    c.drawCentredString(width/2, y - 160, f"Email: {email}")
    c.drawCentredString(width/2, y - 180, f"has successfully completed the quiz.")

    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width/2, y - 210, f"Score: {score}/10")

    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width/2, 100, "Generated by Python Streamlit Quiz App")

    c.save()
    return file_name


st.set_page_config(page_title="Quiz App", page_icon=r"C:\Users\Lokesh\Downloads\techmaa_org.jpg", layout="centered") 
if "page" not in st.session_state:
    st.session_state.page = "login"
if "score" not in st.session_state:
    st.session_state.score = 0
if "current_q" not in st.session_state:
    st.session_state.current_q = 0
if "user" not in st.session_state:
    st.session_state.user = {}

if st.session_state.page == "login":
    st.title("Welcome to Quiz by Techmaa Org.")
    img = Image.open(r"C:\Users\Lokesh\Downloads\techmaa_org.jpg")
    img = img.resize((70,70)) 

    st.image(img)
    st.subheader("Please enter your details to continue:")
    name = st.text_input("Name")
    email = st.text_input("Email")
    dept = st.text_input("Department")

    if st.button("Start Quiz"):
        if not name or not email or not dept:
            st.error("⚠️ Please fill all fields before starting the quiz.")
        else:
            st.session_state.user = {"name": name, "email": email, "department": dept}
            st.session_state.page = "quiz"
            st.rerun()


elif st.session_state.page == "quiz":
    q_index = st.session_state.current_q
    question, options, answer = questions[q_index]

    st.title("🧩 Python Quiz")
    st.subheader(f"Question {q_index + 1} of {len(questions)}")
    st.write(question)

    selected = st.radio("Choose your answer:", options, key=f"q_{q_index}")

    if st.button("Next"):
        if selected == answer:
            st.session_state.score += 1

        if q_index + 1 < len(questions):
            st.session_state.current_q += 1
            st.rerun()()
        else:
            st.session_state.page = "result"
            st.rerun()


elif st.session_state.page == "result":
    name = st.session_state.user["name"]
    email = st.session_state.user["email"]
    dept = st.session_state.user["department"]
    score = st.session_state.score

    st.title("🎉 Quiz Completed!")
    st.success(f"Congratulations {name}! You scored {score}/10.")

    file_path = generate_certificate(name, email, dept, score)

    with open(file_path, "rb") as f:
        st.download_button(
            label="📄 Download Certificate",
            data=f,
            file_name=file_path,
            mime="application/pdf"
        )

    st.write("---")
    st.button("🔁 Take Quiz Again", on_click=lambda: st.session_state.update({
        "page": "login", "score": 0, "current_q": 0
    }))
